services:
  service_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_1
    ports:
      - '3000:3000'
    networks:
      - lab2-net

networks:
  lab2-net:
    external: true
