services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service_1
      - service_2

  service_1:
    extends:
      file: ./service_1/docker-compose.yml
      service: service_1
    container_name: service_1

  service_2:
    extends:
      file: ./service_2/docker-compose.yml
      service: service_2
    container_name: service_2
