worker_processes auto;
events { worker_connections 1024; }

http {
  resolver 127.0.0.11 ipv6=off;

  server {
    listen 80;

    location /api/service-7/ {
      proxy_pass http://service_7:3000/;
    }

    location /api/service-8/ {
      proxy_pass http://service_8:3001/;
    }
  }
}
