worker_processes auto;
events { worker_connections 1024; }

http {
  resolver 127.0.0.11 ipv6=off valid=10s;

  server {
    listen 80;

    location /api/service-7/ {
      set $upstream "service_7:3000";
      proxy_pass http://$upstream/;
    }

    location /api/service-8/ {
      set $upstream "service_8:3001";
      proxy_pass http://$upstream/;
    }
  }
}
