services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lab2-net

networks:
  lab2-net:
    external: true
