services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - gateway_logs:/var/log/nginx
    networks:
      - lab4-net

networks:
  lab4-net:
    external: true

volumes:
  gateway_logs:
    name: gateway_logs
