input {
  file {
    path => "/logs/gateway/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
  file {
    path => "/logs/service_5/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
  file {
    path => "/logs/service_6/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  if [timestamp] {
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "lab-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug { metadata => false } }
}
