input {
  gelf { port => 12201 use_tcp => false }
}

filter {
  # NEW: подчистим message от лидирующих/хвостовых пробелов
  mutate { strip => ["message"] }

  # было: if [message] =~ "^{.*}$"
  if [message] =~ "^\s*{.*}\s*$" {
    json { source => "message" }
  }

  # 2) Выставим @timestamp из полей времени, если есть
  if [time] {
    date { match => ["time","ISO8601","UNIX_MS"] target => "@timestamp" }
  } else if [timestamp] {
    date { match => ["timestamp","UNIX","UNIX_MS"] target => "@timestamp" }
  }

  # 3) Перенесём докер-лейблы/переменные
  mutate {
    rename => { "_app" => "app" }
    rename => { "_service" => "service" }
    rename => { "_env" => "env" }
  }

  # 4) Единое поле request_id (coalesce: pino → nginx upstream → nginx in → заголовок)
  ruby {
    code => '
      rid = event.get("[req][id]") ||
            event.get("x_request_id_upstream") ||
            event.get("x_request_id_in") ||
            (event.get("[headers]") && event.get("[headers]")["x-request-id"])
      event.set("request_id", rid) if rid
    '
  }

  # 5) Удобные алиасы
  if [req][url] and ![path]   { mutate { add_field => { "path" => "%{[req][url]}" } } }
  if [res][statusCode] and ![status] { mutate { add_field => { "status" => "%{[res][statusCode]}" } } }
}


output {
  elasticsearch { hosts => ["http://elasticsearch:9200"] index => "lab4-%{+YYYY.MM.dd}" }
  stdout { codec => rubydebug }
}
